---
my_fonts:
  - hack

terminal_profiles:
  - Peppermint

downloads: ~/.ansible-downloads/

dockitems_enabled: []
dockitems_disabled:
  - Siri
  - Launchpad
  - Contacts
  - Notes
  - Reminders
  - Maps
  - Photos
  - Messages
  - FaceTime
  - Pages
  - Numbers
  - Keynote
  - iTunes
  - iBooks
  - App Store
  - System Preferences

homebrew_installed_packages:
  - autoconf
  - aspell
  - augeas
  - colordiff
  - dockutil
  - fabric
  - geoip
  - gawk
  - git
  - hub
  - ipcalc
  - iperf
  - jq
  - minicom
  - mtr
  - nmap
  - npm
  - nvm
  - packer
  - ssh-copy-id
  - readline
  - rename
  - shellcheck
  - speedtest_cli
  - ssh-copy-id
  - task
  - tig
  - tmux
  - watch
  - weechat
  - wget
  - zsh-completions

homebrew_taps:
  - homebrew/core
  - caskroom/cask
  - homebrew/binary
  - homebrew/dupes
  - homebrew/versions

homebrew_cask_appdir: /Applications
homebrew_cask_apps:
  - 1password
  - alfred
  - atom
  - authy-desktop
  - bartender
  - burn
  - docker
  - dropbox
  - easysimbl
  - filezilla
  - firefox
  - google-chrome
  - gpgtools
  - handbrake
  - istat-menus
  - kdiff3
  - little-snitch
  - macdown
  - macvim
  - makemkv
  - qblocker
  - ripit
  - totalspaces
  - tunnelblick
  - unrarx
  - slack
  - the-unarchiver
  - vagrant
  - virtualbox
  - vlc
  - vmware-fusion
  - xquartz

system_global_gems:
  - name: tmuxinator
    version: 0.9.0
