---
- name: Get current Default Terminal profile.
  command: defaults read com.apple.Terminal 'Default Window Settings'
  register: terminal_theme
  changed_when: false

- name: Ensure custom Terminal profile is added.
  command: open "{{ role_path }}/files/{{ item }}.terminal"
  changed_when: false
  when: "'{{ item }}' not in terminal_theme.stdout"
  with_items: "{{ terminal_profiles }}"

- name: Set Terminal profile is set as default window.
  command: "defaults write com.apple.Terminal 'Default Window Settings' -string '{{ item }}'"
  changed_when: false
  when: "'{{ item }}' not in terminal_theme.stdout"
  with_items: "{{ terminal_profiles }}"

- name: Set Terminal profile is set as default startup window.
  command: "defaults write com.apple.Terminal 'Startup Window Settings' -string '{{ item }}'"
  changed_when: false
  when: "'{{ item }}' not in terminal_theme.stdout"
  with_items: "{{ terminal_profiles }}"

