---
  - hosts: fett
    connection: local

    roles:
      - {role: geerlingguy.homebrew}

    post_tasks:
      - name: Set zsh as shell
        shell: defaults write com.apple.Terminal 'Shell' -string '/bin/zsh'

      - name: Remove all crap from Dock
        shell: dockutil --remove '{{ item }}'
        ignore_errors: true
        with_items: dockitems_to_remove
