---
- name: Install the yoshi testing stuff
  hosts: yoshi
  connection: local

  #Homebrew actually recommend
  pre_tasks:
    - name: Overcome /usr/local perms issues
      file:
        path: /usr/local
        state: directory
        mode: 775
        owner: root
        group: admin

  roles:
    - {role: fonts}
    - {role: geerlinguy.homebrew}
    - {role: mac_terminal}
    - {role: fubarhouse.macdock}

  post_tasks:
    - name: Set zsh as shell
      command: defaults write com.apple.Terminal 'Shell' -string '/bin/zsh'
