---
- hosts: yoshi
  connection: local

  roles:
    - {role: fonts}
    - {role: geerlingguy.homebrew}
    - {role: mac_terminal}
    - {role: fubarhouse.macdock}
    - {role: system_global_gems}
    - {role: system_global_pips}

  post_tasks:
    - name: Require Password for Screen Saver immediately
      command: defaults write com.apple.screensaver askForPasswordDelay 0

    - name: Set zsh as shell
      command: chsh -s /bin/zsh 
