---
- hosts: yoshi
  connection: local

  roles:
    - {role: fonts}
    - {role: geerlingguy.homebrew}
    - {role: mac_terminal}
    - {role: fubarhouse.macdock}
    - {role: system_global_gems}

  post_tasks:
    - name: Set zsh as shell
      command: defaults write com.apple.Terminal 'Shell' -string '/bin/zsh'
