---
- hosts: yoshi
  connection: local

  roles:
    - {role: fonts}
    - {role: geerlinguy.homebrew}
    - {role: mac_terminal}
    - {role: fubarhouse.macdock}

  post_tasks:
    - name: Set zsh as shell
      command: defaults write com.apple.Terminal 'Shell' -string '/bin/zsh'
