---
- name: Install powerline fonts and bindings
  hosts: yoshi
  connection: local
  become: False
  
  tasks:
    - name: Install powerline as a local python package
      pip:
        name: git+https://github.com/Lokaltog/powerline
        executable: /usr/local/bin/pip2
        extra_args:
          - user

    - name: Clone the patched fonts
      git:
        repo: https://github.com/powerline/fonts.git
        dest: ~/.font/sources
        version: master

    - name: Run the patched font installer
      command: sh ~/.font/sources/fonts/install.sh
      register: pline_finstall_out

